steps:
# Prepare config file with the version
- name: 'alpine'
  env:
    - 'VERSION=${_VERSION}'
  args: ['sh', '-c', 'apk add gettext; envsubst <setup.cfg_cloud >setup.cfg']

# Build for a single Python version
- name: 'python:${_PY_VERSION}-alpine3.14'
  args: ['sh', '-c', 'python -mvenv .env']
- name: 'python:${_PY_VERSION}-alpine3.14'
  args: ['sh', '-c', '.env/bin/pip3 install -q -r requirements/base.txt']
- name: 'python:${_PY_VERSION}-alpine3.14'
  args: ['sh', '-c', '.env/bin/pex --disable-cache . -r requirements/base.txt -c elastic-blast -o elastic-blast${_PY_VERSION}']

substitutions:
  _TARGET: 'gs://elasticblast-test/builds'

artifacts:
  objects:
    location: '${_TARGET}/${_VERSION}'
    paths: 'elastic-blast${_PY_VERSION}'